apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: docker
spec:
  selector:
    matchLabels:
      app: docker
  replicas: 2
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: docker-container
          image: bishal29/springbootdemo:latest
          ports:
            - containerPort: 8080