apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo-deployment
  labels:
    app: docker-k8s-demo
spec:
  replicas: 1
  selector:
    matchlabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
spec:
  containers:
  - name: docker-k8s-demo
    image: bishal29/springbootdemo
    ports:
    - containerPort: 8080